<!-- this is the inc file for the footer it is written just like an html file but it is added at the end of every php file-->

<footer> 
<div class="valid">
<a class="button" href="http://validator.w3.org/check/referer">
<span class="bold">HTML</span> Valid!</a>
&nbsp;
<a class="button" href="http://jigsaw.w3.org/css-validator/check/referer?profile=css3">
<span class="bold">CSS</span> Valid!</a>
</div>
<!-- It isn't nessessary in the final version of the website, right now it is just for development purposes, if you want to rid yourself of the aweful thing just change the height and width in the css, dont remove it from the html. But if you are going to keep it, and want to change it, just remove and add divs: however, if you want to keep it the (for whatever strange and twisted reasons beyond me) leave it alone -->
</footer>
</body>
</html>
