<!DOCTYPE html>
<!-- this is the inc file for the footer it is written just like an html file but it is added at the end of every php file-->
<footer> 
<div class="valid">
<a class="button" href="http://validator.w3.org/check/referer">
<span class="bold">HTML</span> Valid!</a>
&nbsp;
<a class="button" href="http://jigsaw.w3.org/css-validator/check/referer?profile=css3">
<span class="bold">CSS</span> Valid!</a>
</div>
</footer>
</html>
