<!DOCTYPE html>
<!--this is the inc file for the headesr it works just like html and is inserted into any body file-->
<html lang ="en">
<link rel="stylesheet" href="static/css/header.css">
<header>
<!--this is for the mobile functionality the navburger is the three horisontal lines in the top right of the mobile version-->
<div id="navb"><img src="static/media/navburger.svg" alt="navigation icon">
</div>
<div id="close" class="hide"><img src="static/media/exit.svg" alt="navigation exit button"></div>

<!--this list is for the nav bar-->
<nav id="mainNav">

    <span id="other">
        <div id="button">About
            <div id="dropdown">
                <a id="content">ok</a>
                <a id="content">ok</a>
                <a id="content">ok</a>
                <a id="content">ok</a>
            </div>
        </div>
    </span>

    <span id="other">
        <div id="button">History
            <div id="dropdown">
                <a id="content">ok</a>
                <a id="content">ok</a>
                <a id="content">ok</a>
                <a id="content">ok</a>
            </div>
        </div>
    </span>

    <span id="other">
        <div id="button">Projects
            <div id="dropdown">
                <a id="content">ok</a>
                <a id="content">ok</a>
                <a id="content">ok</a>
                <a id="content">ok</a>
            </div>
        </div>
    </span>

    <span id="logo">
        <img src="static/media/techlogo.png"></img>
    </span>

    <span id="other">
        <div id="button">News
            <div id="dropdown">
                <a id="content">ok</a>
                <a id="content">ok</a>
                <a id="content">ok</a>
                <a id="content">ok</a>
            </div>
        </div>
    </span>

    <span id="other">
        <div id="button">Links
            <div id="dropdown">
                <a id="content">ok</a>
                <a id="content">ok</a>
                <a id="content">ok</a>
                <a id="content">ok</a>
            </div>
        </div>
    </span>

    <span id="other">
        <div id="button">Apply
            <div id="dropdown">
                <a id="content">ok</a>
                <a id="content">ok</a>
                <a id="content">ok</a>
                <a id="content">ok</a>
            </div>
        </div>
    </span>

</nav>
</header>
</html>
