<!DOCTYPE html>
<!--this is the inc file for the headesr it works just like html and is inserted into any body file-->
<html lang ="en">
<link rel="stylesheet" href="static/css/header.css">
<header>
<!-- the logo is also the home button -->
<a id="logo" href="index.php"><img src="static/media/Olorun.png" alt="Olorun logo"></a>

<!--this is the title of the project-->
<h1>The Olorun Project</h1>

<!--this is for the mobile functionality the navburger is the three hoorisontal lines in the top right of the mobile version-->
<div id="navb"><img src="static/media/navburger.svg" alt="navigation icon">
</div>
<div id="close" class="hide"><img src="static/media/exit.svg" alt="navigation exit button"></div>

<!--this list is for the nav bar-->
<nav id="mainNav">
  <span><a href="about.php">About Olorun</a></span>
  <span><a href="/project">the project</a></span>
  <span><a href="info.php">info</a></span>
  <span><a href="/contact">Contact Us</a></span>
</nav>
</header>
</html>
